"""job progress and stage fields

Revision ID: 35e94f2bccf9
Revises: fddc5f32557b
Create Date: 2026-06-23 21:29:05.804546
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Идентификаторы ревизии Alembic.
revision: str = "35e94f2bccf9"
down_revision: str | None = "fddc5f32557b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # progress — NOT NULL с server_default=0 для backfill существующих строк, затем
    # default снимаем: в модели его нет (значение проставляет приложение), и так
    # `alembic check` остаётся «чистым».
    op.add_column(
        "jobs",
        sa.Column("progress", sa.SmallInteger(), nullable=False, server_default="0"),
    )
    op.alter_column("jobs", "progress", server_default=None)
    op.add_column("jobs", sa.Column("stage", sa.String(length=64), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "stage")
    op.drop_column("jobs", "progress")
    # ### end Alembic commands ###
