"""набор карточек: поле product_id (стадия 3)

Revision ID: fddc5f32557b
Revises: a10c0af96e25
Create Date: 2026-06-23 11:51:52.220528
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Идентификаторы ревизии Alembic.
revision: str = "fddc5f32557b"
down_revision: str | None = "a10c0af96e25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card_sets", sa.Column("product_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_card_sets_product_id"), "card_sets", ["product_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_card_sets_product_id_products"),
        "card_sets",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_card_sets_product_id_products"), "card_sets", type_="foreignkey")
    op.drop_index(op.f("ix_card_sets_product_id"), table_name="card_sets")
    op.drop_column("card_sets", "product_id")
    # ### end Alembic commands ###
