"""товар: поле ideas_json (стадия 2)

Revision ID: a10c0af96e25
Revises: 0824a656fc7e
Create Date: 2026-06-23 11:43:11.953622
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Идентификаторы ревизии Alembic.
revision: str = "a10c0af96e25"
down_revision: str | None = "0824a656fc7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("ideas_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "ideas_json")
    # ### end Alembic commands ###
